config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  namespace :admin do
    resources :author
    resources :publishers
    resources :books
  end

  get 'catalog/index'
  get 'catalog/show'
  get 'catalog/show/:id', to: 'catalog#show'
  get 'catalog/search'
  get 'catalog/search/:id', to: 'catalog#search'
  get 'catalog/latest'
  get 'catalog/latest/:id', to: 'catalog#latest'
  get 'catalog/rss', format: 'application/xml'
  patch '/book/:id/move', to: 'catalog#move'
  get 'catalog/data'

  post 'add', to: 'cart#add'
  delete 'remove', to: 'cart#remove'
  delete 'clear', to: 'cart#clear'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authors_books, dependent: :destroy
  has_many :authors, through: :authors_books

  belongs_to :publisher

  # blobs to load an image
  has_one_attached :cover_image

  # Shoping Cart Implementation
  has_many :cart_items
  has_many :carts, through: :cart_items

  # PG_Search Implementation
  include PgSearch::Model
  pg_search_scope :search_by_title, against: [:title]
  pg_search_scope :search_by_authors, associated_against: {
    authors: %i[first_name last_name]
  }

  validates :title, length: { in: 1..255 }
  validates :publisher, presence: true
  validates :authors, presence: true
  validates :published_at, presence: true
  validates :page_count, numericality: { only_integer: true }
  validates :price, numericality: true
  validates :isbn, format: { with: /[0-9\-xX]{13}/ }
  validates :isbn, uniqueness: true

  def author_names
    authors.map(&:name).join(', ')
  rescue StandardError
    ''
  end

  def self.latest
    order(:id).limit(10)
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :set_admin_book, only: %i[show edit update destroy]

  def index
    @page_title = 'Listing books'
    @books = Book.includes(:publisher)
  end

  def show
    @book = Book.find(params[:id])
    @page_title = @book.title.to_s
  end

  def new
    @book = Book.new
    @publishers = Publisher.all
    @authors = Author.all
  end

  def edit
    @page_title = 'Editing book'
    @book = Book.find(params[:id])
    @publishers = Publisher.all
    @authors = Author.all
  end

  def create
    @book = Book.new(admin_book_params)
    @publishers = Publisher.all
    @authors = Author.all

    respond_to do |format|
      if @book.save
        format.html { redirect_to admin_books_url, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(admin_book_params)
        format.html { redirect_to admin_book_url(@book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to admin_books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_admin_book
    @book = Book.find(params[:id])
  end

  def admin_book_params
    params.require(:book).permit(
      :title,
      :publisher_id,
      :published_at,
      :isbn,
      :blurb,
      :page_count,
      :price,
      :cover_image,
      author_ids: []
    )
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/views/admin/books/_edit_form.html.erb
<%= form_with scope: :book, url: admin_book_url, method: :put do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div>
<p><label for="book_title">Title</label><br/>
<%= text_field 'book', 'title' %></p>

<p><label for="book_publisher">Publisher</label><br/>
<%= collection_select :book, :publisher_id, @publishers, :id, :name %></p>

<p><label for="book[author_ids][]">Authors</label><br/>
<%= select_tag 'book[author_ids][]', options_from_collection_for_select(@authors, :id, :name, @book.authors.collect{ |author| author.id }), { :multiple => true, :size => 5 } %></p>

<p><label for="book_published_at">Published at</label><br/>
<%= datetime_select 'book', 'published_at' %></p>

<p><label for="book_isbn">Isbn</label><br/>
<%= text_field 'book', 'isbn' %></p>

<p><label for="book_blurb">Blurb</label><br/>
<%= text_area 'book', 'blurb' %></p>

<p><label for="book_price">Price</label><br/>
<%= text_field 'book', 'price' %></p>

<p><label for="book_price">Page count</label><br/>
<%= text_field 'book', 'page_count' %></p>

<%= form.label "Book Cover Image"%>
<%= form.file_field :cover_image %></p>
</div>

<div class="actions">
  <%= form.submit %>
</div>

<% end %>

app/views/admin/books/_form.html.erb
<%= form_with scope: :book, url: admin_books_url do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div>
<p><label for="book_title">Title</label><br/>
<%= text_field 'book', 'title' %></p>

<p><label for="book_publisher">Publisher</label><br/>
<%= collection_select :book, :publisher_id, @publishers, :id, :name %></p>

<p><label for="book[author_ids][]">Authors</label><br/>
<%= select_tag 'book[author_ids][]', options_from_collection_for_select(@authors, :id, :name, @book.authors.collect{ |author| author.id }), { :multiple => true, :size => 5 } %></p>

<p><label for="book_published_at">Published at</label><br/>
<%= datetime_select 'book', 'published_at' %></p>

<p><label for="book_isbn">Isbn</label><br/>
<%= text_field 'book', 'isbn' %></p>

<p><label for="book_blurb">Blurb</label><br/>
<%= text_area 'book', 'blurb' %></p>

<p><label for="book_price">Price</label><br/>
<%= text_field 'book', 'price' %></p>

<p><label for="book_price">Page count</label><br/>
<%= text_field 'book', 'page_count' %></p>

<%= form.label "Book Cover Image"%>
<%= form.file_field :cover_image %></p>
</div>

<div class="actions">
  <%= form.submit %>
</div>

<% end %>

app/views/admin/books/edit.html.erb
<%= render 'edit_form', book: @book %>

<%= link_to 'Show', admin_book_path %> |
<%= link_to 'Back', admin_books_path %>

app/views/admin/books/index.html.erb
<h2>Admin Books</h2>

<table>
  <thead>
    <tr>
      <th><a href="?sort_by=publisher_id">Publisher</a></th>
      <th><a href="?sort_by=title">Title</a></th>
      <th><a href="?sort_by=isbn">ISBN</a></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%=h book.publisher.name %></td>
        <td><%=h book.title %></td>
        <td><%=h book.isbn %></td>
        <td><%= link_to "#{book.title}", admin_book_path(book) %></td>
        <td><%= link_to 'Edit', edit_admin_book_path(book) %></td>
        <td><%= link_to 'Destroy', admin_book_path(book), data: { turbo_method: :delete, confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Book', new_admin_book_path %>

app/views/admin/books/new.html.erb
<h1>New Admin Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', admin_books_path %>

app/views/admin/books/show.html.erb
<dl>
  <dt>Title</dt>
  <dd><%= @book.title %></dd>
  <dt>Publisher</dt>
  <dd><%= @book.publisher.name %></dd>
  <dt>Published at</dt>
  <dd><%= @book.published_at.strftime("%m/%d/%Y at %I:%M%p") %></dd>
  <dt>Authors</dt>
  <dd><%= @book.authors.collect{|author| author.name }.join(', ') %></dd>
  <dt>ISBN</dt>
  <dd><%= @book.isbn %></dd>
  <dt>Blurb</dt>
  <dd><%= @book.blurb %></dd>
  <dt>Price</dt>
  <dd><%= @book.price %></dd>
  <dt>Page count</dt>
  <dd><%= @book.page_count %></dd>
  <dt>Cover image</dt>
  <% if @book.cover_image.nil? %>
  <dd>N/A</dd>
  <% end %>
  <% if @book.cover_image.attached? %>
    <image src="<%=(url_for(@book.cover_image))%>"></image>
  <% end %>
</dl>

<%= link_to 'Edit', edit_admin_book_path(@book) %> |
<%= link_to 'Back', admin_books_path %>