config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  namespace :admin do
    resources :author
    resources :publishers
    resources :books
  end

  get 'catalog/index'
  get 'catalog/show'
  get 'catalog/show/:id', to: 'catalog#show'
  get 'catalog/search'
  get 'catalog/search/:id', to: 'catalog#search'
  get 'catalog/latest'
  get 'catalog/latest/:id', to: 'catalog#latest'
  get 'catalog/rss', format: 'application/xml'
  patch '/book/:id/move', to: 'catalog#move'
  get 'catalog/data'

  post 'add', to: 'cart#add'
  delete 'remove', to: 'cart#remove'
  delete 'clear', to: 'cart#clear'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :books, through: :cart_items

  def total
    cart_items.inject(0) { |sum, n| (n.price * n.amount) + sum }
  end

  def add(book_id)
    items = cart_items.find_by(book_id: book_id)
    book = Book.find(book_id)

    if items.to_s.empty?
      cart_item = cart_items.create(book_id: book_id, amount: 1, price: book.price)
    else
      cart_item = items
      cart_item.update_attribute(:amount, cart_item.amount + 1)
    end
    cart_item
  end

  def remove(book_id)
    ci = cart_items.find_by(book_id: book_id)

    if ci.amount > 1
      ci.update_attribute(:amount, ci.amount - 1)
    else
      CartItem.destroy(ci.id)
    end
    ci
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :initialize_cart

  def add
    @book = Book.find(params[:id])
    @item = @cart.add(params[:id])

    respond_to do |format|
      flash[:cart_notice] = "Book added #{@item.book.title}"
      # The ajax request could respond with an html
      format.html { redirect_to catalog_index_path }
      # format.js
    end
  end

  def remove
    @book = Book.find(params[:id])
    @item = @cart.remove(params[:id])

    respond_to do |format|
      flash[:cart_notice] = "Book removed #{@item.book.title}"
      format.html { redirect_to catalog_index_path }
    end
  end

  def clear
    @cart.cart_items.destroy_all
    respond_to do |format|
      flash[:cart_notice] = 'Cleared the cart'
      format.html { redirect_to catalog_index_path }
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart.html.erb
<div style="height: 100%" data-controller="droppable" data-action="drop->droppable#drop dragover->droppable#dragOver">
  <div class="container_cart_close_button">
    <%= link_to "X", class: "cart_close_button" %>
  </div>

  <% if flash[:cart_notice] %>
    <%= render partial: "cart/cart_notice" %>
  <% end %>

  <h3>Your Shopping Cart</h3>

  <ul>
    <% @cart.cart_items.each { |item| %>
      <li id="cart_item_<%= item.book.id %>">
        <%= render partial: 'cart/item', object: item %>
      </li>
    <% } %>
  </ul>

  <p id="cart_total"><strong>Total: $<%= sprintf("%0.2f", @cart.total) %></strong></p>

  <% unless @cart.cart_items.empty? %> <p id="clear_cart_link">
  <small>
    <%= button_to 'Clear cart', clear_path, method: :delete, remote: true, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "clear_cart" %>
  </small>
</p>
  <% end %>
</div>

app/views/cart/_cart_notice.html.erb
<p id="cart_notice"><%= flash[:cart_notice] %></p>

app/views/cart/_item.html.erb
<%= link_to item.book.title, action: "show", controller: "catalog", id: item.book.id %>
<%= pluralize(item.amount, "pc", "pcs") %>, $<%= sprintf("%0.2f", item.price * item.amount) %>

<!-- We can also set data: { turbo: "false" } if we don't want our request to be Ajax -->
<%= button_to 'Remove book', remove_path(id: item.book.id), method: :delete, remote: true, form: { data: { turbo_confirm: 'Are you sure?' } } %>

app/views/cart/add.js.erb
const element = document.getElementById('shopping-cart');

element.style.backgroundColor = 'blue';

console.log('Hello there my friend!')

app/views/cart/add_with_ajax.js.erb
const element = document.getElementById('shopping-cart');

element.style.backgroundColor = 'blue';