config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  namespace :admin do
    resources :author
    resources :publishers
    resources :books
  end

  get 'catalog/index'
  get 'catalog/show'
  get 'catalog/show/:id', to: 'catalog#show'
  get 'catalog/search'
  get 'catalog/search/:id', to: 'catalog#search'
  get 'catalog/latest'
  get 'catalog/latest/:id', to: 'catalog#latest'
  get 'catalog/rss', format: 'application/xml'
  patch '/book/:id/move', to: 'catalog#move'
  get 'catalog/data'

  post 'add', to: 'cart#add'
  delete 'remove', to: 'cart#remove'
  delete 'clear', to: 'cart#clear'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  before_action :initialize_cart

  PER_PAGE = 3

  def index
    @page_title = 'Book List'
    @book_pages = params.fetch(:page, 0).to_i
    @books = Book.includes(:authors, :publisher).offset(@book_pages * PER_PAGE).limit(PER_PAGE)
  end

  def show
    @book = begin
      Book.find(params[:id])
    rescue StandardError
      nil
    end
    return render(text: 'Not found', status: 404) unless @book

    @page_title = @book.title
  end

  def search
    @page_title = 'Search'

    return unless params[:commit] == 'Search' || params[:q]

    @books = Book.search_by_title(params[:q].to_s.upcase)
    flash.now[:notice] = 'No books found matching your criteria' unless @books.size.positive?
  end

  def latest
    @page_title = 'Latest Books'
    @books = Book.latest
  end

  def rss
    latest
    render layout: false
  end

  def move
    @book = Book.find(params[:id])
    @book.insert_at(params[:position].to_i)
    head :ok
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/views/catalog/_books.erb
<ul id="books" data-controller="draggable">
  <% @books.each { |book| %>
    <li class="book" data-id="<%= book.id %>" draggable="true" data-draggable-target="book"
        data-action="dragstart->draggable#dragStart dragenter->draggable#dragEnter dragover->draggable#dragOver dragleave->draggable#dragLeave dragend->draggable#dragEnd">
      <dl>
        <dt><%= link_to book.title, action: "show", id: book %></dt>
        <dt><%= book.title %></dt>

        <% book.authors.each { |author| %>
          <dd><%= author.last_name %>, <%= author.first_name %></dd>
        <% } %>

        <dd><%= pluralize(book.page_count, "page") %></dd>
        <dd>Price: <%= number_to_currency(book.price) %></dd>
        <dd><small>Publisher: <%=  book.publisher.name %></small></dd>

        <dd>
          <strong>
            <!-- We can also set data: { turbo: "false" } if we don't want our request to be Ajax -->
            <%= button_to 'Click or drag to the cart', add_path(id: book.id), method: :post, remote: true, form: {data: {turbo_confirm: 'Are you sure?'}} %>
          </strong>
        </dd>
      </dl>
    </li>
  <% } %>
</ul>

app/views/catalog/_search_box.erb
<%= form_tag catalog_search_path, method: :get do %>
  <%= text_field_tag :q %>
  <%= submit_tag "Search" %>
<% end %>

app/views/catalog/index.html.erb
<p><%= link_to "Search", action: "search" %></p>

<%= render(partial: "books") %>

<div>
  <% if @book_pages > 0 %>
    <%= link_to 'Previous page', catalog_index_path(page: @book_pages - 1) %> |
  <% end %>
  <%= link_to 'Next page', catalog_index_path(page: @book_pages + 1) %>
</div>

app/views/catalog/latest.html.erb
<%= render partial: "books" %>

app/views/catalog/search.html.erb
<%= render partial: "search_box" %>

<% if @books %>
  <p>Your search "<%= params[:q] %>" produced
  <%= pluralize @books.size, "result" %>:</p>
  <%= render(partial: "books") %>
<% end %>

app/views/catalog/show.html.erb
<h2>by <%= @book.authors.map{|a| a.name}.join(", ") %></h2>
<image src="<%= (url_for(@book.cover_image)) unless @book.cover_image.blank? %>"></image>
<dl>
  <dt>Price</dt>
  <dd><%= number_to_currency(@book.price) -%></dd>
  <dt>Page count</dt>
  <dd><%= @book.page_count -%></dd>
  <dt>Publisher</dt>
  <dd><%= @book.publisher.name%></dd>
  <dt>Blurb</dt>
  <dd><%= @book.blurb%></dd>
</dl>

<p><%= link_to "Back to Catalog", action: "index" %></p>