config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  namespace :admin do
    resources :author
    resources :publishers
    resources :books
  end

  get 'catalog/index'
  get 'catalog/show'
  get 'catalog/show/:id', to: 'catalog#show'
  get 'catalog/search'
  get 'catalog/search/:id', to: 'catalog#search'
  get 'catalog/latest'
  get 'catalog/latest/:id', to: 'catalog#latest'
  get 'catalog/rss', format: 'application/xml'
  patch '/book/:id/move', to: 'catalog#move'
  get 'catalog/data'

  post 'add', to: 'cart#add'
  delete 'remove', to: 'cart#remove'
  delete 'clear', to: 'cart#clear'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, length: { in: 2..255 }
  validates :name, uniqueness: true
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  before_action :set_publisher, only: %i[show edit update destroy]

  def index
    @publishers = Publisher.all
  end

  def show
    @page_title = @publisher.name
  end

  def new
    @publisher = Publisher.new
  end

  def edit; end

  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to admin_publisher_url(@publisher), notice: 'Publisher was successfully created.' }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to admin_publisher_url(@publisher), notice: 'Publisher was successfully updated.' }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @publisher.destroy

    respond_to do |format|
      format.html { redirect_to admin_publishers_url, notice: 'Publisher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_publisher
    @publisher = Publisher.find(params[:id])
  end

  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/admin/publishers_helper.rb
module Admin::PublishersHelper
end

app/views/admin/publishers/_edit_form.html.erb
<%= form_with scope: :publisher, url: admin_publisher_url, method: :put do |form| %>
  <% if publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
        <% publisher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: 'Name' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/publishers/_form.html.erb
<%= form_with scope: :publisher, url: admin_publishers_url do |form| %>
  <% if publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
        <% publisher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: 'Name' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/publishers/edit.html.erb
<h1>Editing Publisher</h1>

<%= render 'edit_form', publisher: @publisher %>

<%= link_to 'Show', admin_publisher_path %> |
<%= link_to 'Back', admin_publishers_path %>

app/views/admin/publishers/index.html.erb
<h1>Publishers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= link_to "#{publisher.name}", admin_publisher_path(publisher) %></td>
        <td><%= link_to 'Edit', edit_admin_publisher_path(publisher) %></td>
        <td><%= link_to 'Destroy', admin_publisher_path(publisher), data: { "turbo-method": :delete, confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publisher', new_admin_publisher_path %>

app/views/admin/publishers/new.html.erb
<h1>New Publisher</h1>

<%= render 'form', publisher: @publisher %>

<%= link_to 'Back', admin_publishers_path %>

app/views/admin/publishers/show.html.erb
<dl>
  <dt>Name</dt>
  <dd><%= @publisher.name %></dd>
</dl>

<%= link_to 'Edit', edit_admin_publisher_path(@publisher) %> |
<%= link_to 'Back', admin_publishers_path %>